/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import geral.InterProcessor;
import geral.Maskable;
import geral.Metodo;
import geral.NonMaskable;
import geral.Processo;
import geral.Software;
import gerenciador.Interrupcao;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sabrina Winckler
 */
public class view extends javax.swing.JFrame {

    Interrupcao interrupcao;
    ArrayList<Processo> proccessosParados = new ArrayList();
    ArrayList<Processo> processosEmExecucao = new ArrayList();
//    private Processo vetorProcessos[] = new Processo();
    private DefaultTableModel modelTabela;

    /**
     * Creates new form view
     */
    public view() {
        this.interrupcao = new Interrupcao();
        initComponents();
        this.modelTabela = (DefaultTableModel) this.jTable1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        step = new javax.swing.JButton();
        nomeProcesso = new javax.swing.JTextField();
        prioridade = new javax.swing.JTextField();
        tipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(this.modelTabela = new DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Processo", "Tipo", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        step.setText("Adicionar Processo");
        step.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepActionPerformed(evt);
            }
        });

        nomeProcesso.setText("Nome do processo");

        prioridade.setText("0");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software", "NonMaskable", "Maskable", "InterProcessor" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(step, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nomeProcesso)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prioridade))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(prioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(step)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepActionPerformed
        Random rand = new Random();
        int tamanho = rand.nextInt();
        int tempoCheg = rand.nextInt();
        int tempoExec = rand.nextInt();
        int p = Integer.parseInt(prioridade.getText());
        String nome = nomeProcesso.getText();
        Metodo m = null;
        if (tipo.getSelectedIndex() == 0) {
            m = new Software();
        } else if (tipo.getSelectedIndex() == 1) {
            m = new NonMaskable();
        } else if (tipo.getSelectedIndex() == 2) {
            m = new Maskable();
        } else if (tipo.getSelectedIndex() == 3) {
            m = new InterProcessor();
        }
        Processo processo = new Processo(nome, tamanho, tempoCheg, tempoExec, p, m);
        interrupcao.addProcesso(processo);
        this.processosEmExecucao.add(processo);
        interrupcao.bloquear();
        this.modelTabela.setRowCount(0);
        for (Processo pr : this.interrupcao.getListaProcessos()) {
            this.modelTabela.addRow(new Object[]{
                pr.getNome(),
                pr.getTipo().getClass().getName().split("\\.")[1],
                pr.isStop() ? "Parado" : "Executando"
            });
        } 
        
//        this.jTable1.getModel().setValueAt(processo.getNome(), 0, 0);
    }//GEN-LAST:event_stepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    public void verificarProcessoParado(Processo processo) {
        if (processo.isStop()) {
            this.proccessosParados.add(processo);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nomeProcesso;
    private javax.swing.JTextField prioridade;
    private javax.swing.JButton step;
    private javax.swing.JComboBox<String> tipo;
    // End of variables declaration//GEN-END:variables
}
